robot:
  - 
    name: "MIDJAXON"
    plugin: Body
    class: BodyItem
    positionOffset: [0, 0, -0.7]
    data: 
      modelFile: "../../jvrc_models/JAXON_JVRC/MIDJAXON.wrl"
      currentBaseLink: "WAIST"
      jointPositions: [ 
      0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.349066,  0.000000, -1.396263, 
      0.000000,  0.000000,  0.000000,  0.000000,  0.000000, -0.349066,  0.000000, -1.396263, -0.000000,  0.000000, 
      0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000, 
      0.000000,  0.000000,  0.000000,  0.000000,  0.000000,  0.000000 ]
      zmp: [ 0, 0, 0 ]
      collisionDetection: true
      selfCollisionDetection: false
      isEditable: true
    children: 
      - 
        name: "BodyRTC"
        plugin: OpenRTM
        class: BodyRTCItem
        data: 
          isImmediateMode: true
          moduleName: "/home/player/rtmros_choreonoid/hrpsys_choreonoid/src/PDcontroller"
          confFileName: "/home/player/rtmros_choreonoid/hrpsys_ros_bridge_jvrc/config/MIDJAXON.PD.conf"
          configurationMode: Use Configuration File
          AutoConnect: false
          InstanceName: MIDJAXON
          bodyPeriodicRate: 0.002
sensors:
  - 
    name: "GLVisionSimulator"
    plugin: Body
    class: GLVisionSimulatorItem
    data: 
      enabled: true
      targetBodies: [ MIDJAXON ]
      targetSensors: [ ]
      maxFrameRate: 1000
      maxLatency: 1
      recordVisionData: false
      useThread: true
      useThreadsForSensors: true
      bestEffort: false
      allSceneObjects: false
      rangeSensorPrecisionRatio: 2
      depthError: 0
      enableHeadLight: true
      enableAdditionalLights: true
